version: '2'
services:
  codereviewersapplication-app:
    image: codereviewersapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://codereviewersapplication-postgresql:5432/codereviewers
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/codereviewers
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  codereviewersapplication-postgresql:
    extends:
      file: postgresql.yml
      service: codereviewersapplication-postgresql
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak